services:
  r1:
    build: ./frr
    container_name: bgplab-r1
    privileged: true
    networks:
      lab:
        ipv4_address: 172.20.0.2

  dev:
    build: ./dev
    container_name: bgplab-dev
    volumes:
      - ./app:/app
    working_dir: /app
    command: sleep infinity
    networks:
      lab:
        ipv4_address: 172.20.0.3

networks:
  lab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
